BENCHMARK_DATASETS:
   # Small values
   - 'GTEx/GTEx_T2_N4_G100'
   # Fix N=100, vary G
   - 'GTEx/GTEx_T10_N100_G10'
   - 'GTEx/GTEx_T10_N100_G100'
   - 'GTEx/GTEx_T10_N100_G1000'
   - 'GTEx/GTEx_T10_N100_G2000'
   - 'GTEx/GTEx_T10_N100_G4000'
   # Fix G=1000, vary N
   - 'GTEx/GTEx_T10_N4_G1000'
   - 'GTEx/GTEx_T10_N10_G1000'
   - 'GTEx/GTEx_T10_N40_G1000'
   - 'GTEx/GTEx_T10_N600_G1000'
   # Fix G=1000, N=10, vary T
   - 'GTEx/GTEx_T2_N10_G1000'
   - 'GTEx/GTEx_T5_N10_G1000'
   - 'GTEx/GTEx_T20_N10_G1000'
   # Large values
   - 'GTEx/GTEx_T10_N600_G4000'

BENCHMARK_METHODS:
   - 'BicMix'
   - 'FABIA'
   - 'MultiCluster'
   - 'nsNMF'
   - 'Plaid'
   - 'SDA'
   - 'SNMF'
   - 'SSLB'

BENCHMARK_DEFAULT_K: 50

BENCHMARK_MAX_GENES: 10000

BENCHMARK_K_DATASET: 'GTEx/GTEx_T10_N10_G1000'

BENCHMARK_K_VALUES: [1, 5, 20, 80, 100, 400]

BENCHMARK_ITER_DATASET: 'GTEx/GTEx_T10_N10_G1000'

BENCHMARK_ITER_MULTIPLIERS: [1e-1, 3e-1, 5e-1, 1, 4, 10, 100]

BENCHMARK_G_DATASET: 'GTEx/GTEx_T10_N100_G1000'
BENCHMARK_N_DATASET: 'GTEx/GTEx_T10_N100_G1000'
BENCHMARK_NT_DATASET: 'GTEx/GTEx_T10_N100_G1000'
BENCHMARK_T_DATASET: 'GTEx/GTEx_T10_N10_G1000'

BENCHMARK_SEEDS: [123456, 314159, 131719]
